name: ActionOrList
definition:
  {
    "oneOf": [
      {
        "$ref": "#/$defs/Action"
      },
      {
        "type": "array",
        "items": {
          "$ref": "#/$defs/Action"
        }
      }
    ]
  }
