name: Typography
definition:
  {
    "type": "object",
    "properties": {
      "displayLarge": {
        "$ref": "#/$defs/TextStyle"
      },
      "displayMedium": {
        "$ref": "#/$defs/TextStyle"
      },
      "displaySmall": {
        "$ref": "#/$defs/TextStyle"
      },
      "headlineLarge": {
        "$ref": "#/$defs/TextStyle"
      },
      "headlineMedium": {
        "$ref": "#/$defs/TextStyle"
      },
      "headlineSmall": {
        "$ref": "#/$defs/TextStyle"
      },
      "titleLarge": {
        "$ref": "#/$defs/TextStyle"
      },
      "titleMedium": {
        "$ref": "#/$defs/TextStyle"
      },
      "titleSmall": {
        "$ref": "#/$defs/TextStyle"
      },
      "bodyLarge": {
        "$ref": "#/$defs/TextStyle"
      },
      "bodyMedium": {
        "$ref": "#/$defs/TextStyle"
      },
      "bodySmall": {
        "$ref": "#/$defs/TextStyle"
      },
      "labelLarge": {
        "$ref": "#/$defs/TextStyle"
      },
      "labelMedium": {
        "$ref": "#/$defs/TextStyle"
      },
      "labelSmall": {
        "$ref": "#/$defs/TextStyle"
      }
    },
    "additionalProperties": false
  }
